const examActionTypes = Object.freeze({
  // Exam CRUD
  CREATE_EXAM_REQUEST: "CREATE_EXAM_REQUEST",
  CREATE_EXAM_SUCCESS: "CREATE_EXAM_SUCCESS",
  CREATE_EXAM_FAILURE: "CREATE_EXAM_FAILURE",
  
  GET_EXAMS_REQUEST: "GET_EXAMS_REQUEST",
  GET_EXAMS_SUCCESS: "GET_EXAMS_SUCCESS",
  GET_EXAMS_FAILURE: "GET_EXAMS_FAILURE",
  
  UPDATE_EXAM_REQUEST: "UPDATE_EXAM_REQUEST",
  UPDATE_EXAM_SUCCESS: "UPDATE_EXAM_SUCCESS",
  UPDATE_EXAM_FAILURE: "UPDATE_EXAM_FAILURE",
  
  DELETE_EXAM_REQUEST: "DELETE_EXAM_REQUEST",
  DELETE_EXAM_SUCCESS: "DELETE_EXAM_SUCCESS",
  DELETE_EXAM_FAILURE: "DELETE_EXAM_FAILURE",
  
  // Exam Management
  SET_SELECTED_EXAM: "SET_SELECTED_EXAM",
  SET_EXAM_FILTER: "SET_EXAM_FILTER",
  CLEAR_EXAM_ERRORS: "CLEAR_EXAM_ERRORS",
  
  // Question Assignment
  ADD_QUESTION_TO_EXAM: "ADD_QUESTION_TO_EXAM",
  REMOVE_QUESTION_FROM_EXAM: "REMOVE_QUESTION_FROM_EXAM",
  REORDER_EXAM_QUESTIONS: "REORDER_EXAM_QUESTIONS",
});

export default examActionTypes;
