const actionTypes = Object.freeze({
  SIGN_UP: "SIGN_UP",
  USER_IS_LOGIN: "USER_IS_LOGIN",
  LOGIN: "LOGIN",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  SET_USER_ROLE: "SET_USER_ROLE",
  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
  LOGOUT: "LOGOUT",
});

export default actionTypes;
