const actionTypes = Object.freeze({
  // Question CRUD
  CREATE_QUESTION_REQUEST: "CREATE_QUESTION_REQUEST",
  CREATE_QUESTION_SUCCESS: "CREATE_QUESTION_SUCCESS",
  CREATE_QUESTION_FAILURE: "CREATE_QUESTION_FAILURE",
  
  GET_QUESTIONS_REQUEST: "GET_QUESTIONS_REQUEST",
  GET_QUESTIONS_SUCCESS: "GET_QUESTIONS_SUCCESS",
  GET_QUESTIONS_FAILURE: "GET_QUESTIONS_FAILURE",
  
  UPDATE_QUESTION_REQUEST: "UPDATE_QUESTION_REQUEST",
  UPDATE_QUESTION_SUCCESS: "UPDATE_QUESTION_SUCCESS",
  UPDATE_QUESTION_FAILURE: "UPDATE_QUESTION_FAILURE",
  
  DELETE_QUESTION_REQUEST: "DELETE_QUESTION_REQUEST",
  DELETE_QUESTION_SUCCESS: "DELETE_QUESTION_SUCCESS",
  DELETE_QUESTION_FAILURE: "DELETE_QUESTION_FAILURE",
  
  // Question Bank Management
  GET_QUESTION_BANKS_REQUEST: "GET_QUESTION_BANKS_REQUEST",
  GET_QUESTION_BANKS_SUCCESS: "GET_QUESTION_BANKS_SUCCESS",
  GET_QUESTION_BANKS_FAILURE: "GET_QUESTION_BANKS_FAILURE",
  
  CREATE_QUESTION_BANK_REQUEST: "CREATE_QUESTION_BANK_REQUEST",
  CREATE_QUESTION_BANK_SUCCESS: "CREATE_QUESTION_BANK_SUCCESS",
  CREATE_QUESTION_BANK_FAILURE: "CREATE_QUESTION_BANK_FAILURE",
  
  // UI States
  SET_SELECTED_QUESTION: "SET_SELECTED_QUESTION",
  SET_QUESTION_FILTER: "SET_QUESTION_FILTER",
  CLEAR_QUESTION_ERRORS: "CLEAR_QUESTION_ERRORS",
});

export default actionTypes;
